export const categoryIcons = {
    "c_1": require('../assets/category-icons/c_1.png'),
    "c_2": require('../assets/category-icons/c_2.png'),
    "c_3": require('../assets/category-icons/c_3.png'),
    "c_4": require('../assets/category-icons/c_4.png'),
    "c_5": require('../assets/category-icons/c_5.png'),
    "c_6": require('../assets/category-icons/c_6.png'),
    "c_7": require('../assets/category-icons/c_7.png'),
    "c_8": require('../assets/category-icons/c_8.png'),
    "c_9": require('../assets/category-icons/c_9.png'),
    "c_10": require('../assets/category-icons/c_10.png'),
    "c_11": require('../assets/category-icons/c_11.png'),
    "c_12": require('../assets/category-icons/c_12.png'),
    "c_13": require('../assets/category-icons/c_13.png'),
    "c_14": require('../assets/category-icons/c_14.png'),
    "c_15": require('../assets/category-icons/c_15.png'),
    "c_16": require('../assets/category-icons/c_16.png'),
    "c_17": require('../assets/category-icons/c_17.png'),
    "c_18": require('../assets/category-icons/c_18.png'),
    "c_19": require('../assets/category-icons/c_19.png'),
    "c_20": require('../assets/category-icons/c_20.png'),
    "c_21": require('../assets/category-icons/c_21.png'),
    "c_22": require('../assets/category-icons/c_22.png')
}